
import { Color } from 'core/classes/Color'

export const HEADS_COLOR: Color = Color.blue()
export const TAILS_COLOR: Color = Color.red()
export const BASE_BRICK_HEIGHT: number = 50
export const BASE_ROW_LENGTH: number = 500
export const FAST_PARTITION_ANIMATION_DURATION: number = 0.25
export const SLOW_PARTITION_ANIMATION_DURATION: number = 0.5
export const BRICK_STROKE_WIDTH: number = 3
export const BRICK_FILL_OPACITY: number = 1.0
export const CELL_SIZE: number = 70
export const CELL_PADDING: number = 10
export const CELL_CORNER_RADIUS: number = 10
export const CELL_STROKE_COLOR: Color = Color.gray(0.5)
export const CELL_STROKE_WIDTH: number = 1
export const CELL_HIGHLIGHT_STROKE_COLOR: Color = Color.white()
export const CELL_HIGHLIGHT_STROKE_WIDTH: number = 5
export const EDGE_COLOR: Color = Color.gray(0.5)
export const EDGE_WIDTH: number = 1
export const EDGE_HIGHLIGHT_COLOR: Color = Color.white()
export const EDGE_HIGHLIGHT_WIDTH: number = 5
export const COIN_WIDTH: number = 20
export const COIN_HEIGHT: number = 4
export const COIN_PADDING: number = 10
export const STACK_MAX_HEIGHT: number = 30
export const HT_LABEL_HEIGHT: number = 15
export const HT_LABEL_PADDING: number = 10
export const COMB_LABEL_WIDTH: number = 40
export const COMB_LABEL_HEIGHT: number = 20
export const CELL_START_OPACITY: number = 0.5
export const FAST_CELL_ANIMATION_DURATION: number = 0.5
export const SLOW_CELL_ANIMATION_DURATION: number = 1
export const PATH_LABEL_SIZE: number = 35
export const PATH_LABEL_FONT_SIZE: number = 24
export const PATH_COIN_ROW_OFFSET_FACTOR: number = 0.85
