export const IO_LIST_WIDTH = 150;
export const IO_LIST_OFFSET = 10;
export const HOOK_RADIUS = 9;
export const BULLET_RADIUS = 7;
export const SNAPPING_DISTANCE = 12.5;
export const HOOK_INSET_X = 15;
export const HOOK_INSET_Y = 15;
export const HOOK_VERTICAL_SPACING = 25;
export const HOOK_LABEL_INSET = 30;
export const LINK_LINE_WIDTH = 5;
//# sourceMappingURL=constants.js.map